// Quiz Questions Bank - 200+ questions per difficulty level

export type Difficulty = 'beginner' | 'intermediate' | 'advanced';

export interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: Difficulty;
}

// Helper function to shuffle array (Fisher-Yates algorithm)
export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

// Select random questions from a pool
export function selectRandomQuestions(
  questions: QuizQuestion[],
  count: number
): QuizQuestion[] {
  const shuffled = shuffleArray(questions);
  return shuffled.slice(0, count);
}

// BEGINNER LEVEL QUESTIONS (200+ questions)
export const beginnerQuestions: QuizQuestion[] = [
  {
    id: 1,
    question: "What does 'forte' mean in music?",
    options: ["Loud", "Soft", "Fast", "Slow"],
    correctAnswer: 0,
    explanation: "Forte (f) is a dynamic marking that means to play loudly.",
    difficulty: 'beginner',
  },
  {
    id: 2,
    question: "How many lines are in a standard musical staff?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 2,
    explanation: "A standard musical staff has 5 lines where notes are placed.",
    difficulty: 'beginner',
  },
  {
    id: 3,
    question: "What is the name of the treble clef?",
    options: ["G clef", "F clef", "C clef", "B clef"],
    correctAnswer: 0,
    explanation: "The treble clef is also known as the G clef because it circles the G line.",
    difficulty: 'beginner',
  },
  {
    id: 4,
    question: "What does 'piano' mean in music?",
    options: ["Loud", "Soft", "Medium", "Very loud"],
    correctAnswer: 1,
    explanation: "Piano (p) is a dynamic marking that means to play softly.",
    difficulty: 'beginner',
  },
  {
    id: 5,
    question: "How many beats does a whole note typically receive in 4/4 time?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 3,
    explanation: "A whole note receives 4 beats in 4/4 time signature.",
    difficulty: 'beginner',
  },
  {
    id: 6,
    question: "What is the relative minor of C major?",
    options: ["G minor", "A minor", "E minor", "D minor"],
    correctAnswer: 1,
    explanation: "A minor is the relative minor of C major, sharing the same key signature (no sharps or flats).",
    difficulty: 'beginner',
  },
  {
    id: 7,
    question: "What note is a half step above C?",
    options: ["B", "C#", "D", "D#"],
    correctAnswer: 1,
    explanation: "C# (C sharp) is a half step above C.",
    difficulty: 'beginner',
  },
  {
    id: 8,
    question: "In 4/4 time, how many beats does a half note receive?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    explanation: "A half note receives 2 beats in 4/4 time signature.",
    difficulty: 'beginner',
  },
  {
    id: 9,
    question: "What is the order of sharps in key signatures?",
    options: ["F-C-G-D-A-E-B", "B-E-A-D-G-C-F", "C-G-D-A-E-B-F#", "F#-B-E-A-D-G-C"],
    correctAnswer: 0,
    explanation: "The order of sharps is F-C-G-D-A-E-B, which can be remembered as 'Father Charles Goes Down And Ends Battle'.",
    difficulty: 'beginner',
  },
  {
    id: 10,
    question: "What is the bass clef also known as?",
    options: ["G clef", "F clef", "C clef", "A clef"],
    correctAnswer: 1,
    explanation: "The bass clef is also known as the F clef because it has two dots on either side of the F line.",
    difficulty: 'beginner',
  },
  {
    id: 11,
    question: "How many sharps are in the key of G major?",
    options: ["0", "1", "2", "3"],
    correctAnswer: 1,
    explanation: "G major has 1 sharp: F#.",
    difficulty: 'beginner',
  },
  {
    id: 12,
    question: "What does a dot after a note do?",
    options: ["Makes it louder", "Adds half its value", "Makes it shorter", "Changes the pitch"],
    correctAnswer: 1,
    explanation: "A dot after a note adds half of its original value to the note's duration.",
    difficulty: 'beginner',
  },
  {
    id: 13,
    question: "What is the time signature 3/4 called?",
    options: ["Common time", "Waltz time", "March time", "Cut time"],
    correctAnswer: 1,
    explanation: "3/4 time is called waltz time because waltzes are typically in 3/4 time.",
    difficulty: 'beginner',
  },
  {
    id: 14,
    question: "What note is a whole step above C?",
    options: ["C#", "D", "D#", "E"],
    correctAnswer: 1,
    explanation: "D is a whole step (two half steps) above C.",
    difficulty: 'beginner',
  },
  {
    id: 15,
    question: "How many flats are in the key of F major?",
    options: ["0", "1", "2", "3"],
    correctAnswer: 1,
    explanation: "F major has 1 flat: Bb.",
    difficulty: 'beginner',
  },
  {
    id: 16,
    question: "What does 'legato' mean?",
    options: ["Short and detached", "Smooth and connected", "Very loud", "Very soft"],
    correctAnswer: 1,
    explanation: "Legato means to play notes smoothly and connected, without gaps between them.",
    difficulty: 'beginner',
  },
  {
    id: 17,
    question: "What does 'staccato' mean?",
    options: ["Short and detached", "Smooth and connected", "Very loud", "Very soft"],
    correctAnswer: 0,
    explanation: "Staccato means to play notes short and detached, with space between them.",
    difficulty: 'beginner',
  },
  {
    id: 18,
    question: "What is a tie in music notation?",
    options: ["A curved line connecting notes of different pitches", "A curved line connecting notes of the same pitch", "A vertical line", "A sharp or flat sign"],
    correctAnswer: 1,
    explanation: "A tie is a curved line connecting notes of the same pitch, combining their durations.",
    difficulty: 'beginner',
  },
  {
    id: 19,
    question: "How many beats does a quarter note receive in 4/4 time?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 0,
    explanation: "A quarter note receives 1 beat in 4/4 time signature.",
    difficulty: 'beginner',
  },
  {
    id: 20,
    question: "What is the symbol for forte?",
    options: ["p", "f", "mp", "mf"],
    correctAnswer: 1,
    explanation: "The symbol 'f' stands for forte, meaning loud.",
    difficulty: 'beginner',
  },
  {
    id: 21,
    question: "What is the symbol for piano (soft)?",
    options: ["p", "f", "mp", "mf"],
    correctAnswer: 0,
    explanation: "The symbol 'p' stands for piano, meaning soft.",
    difficulty: 'beginner',
  },
  {
    id: 22,
    question: "What does 'crescendo' mean?",
    options: ["Gradually getting louder", "Gradually getting softer", "Getting faster", "Getting slower"],
    correctAnswer: 0,
    explanation: "Crescendo means gradually getting louder.",
    difficulty: 'beginner',
  },
  {
    id: 23,
    question: "What does 'diminuendo' or 'decrescendo' mean?",
    options: ["Gradually getting louder", "Gradually getting softer", "Getting faster", "Getting slower"],
    correctAnswer: 1,
    explanation: "Diminuendo (or decrescendo) means gradually getting softer.",
    difficulty: 'beginner',
  },
  {
    id: 24,
    question: "What is the name of the space between two bar lines?",
    options: ["Bar", "Measure", "Phrase", "Section"],
    correctAnswer: 1,
    explanation: "The space between two bar lines is called a measure (or bar in British English).",
    difficulty: 'beginner',
  },
  {
    id: 25,
    question: "What does 'andante' mean?",
    options: ["Very fast", "Walking pace", "Very slow", "Moderate speed"],
    correctAnswer: 1,
    explanation: "Andante means at a walking pace, moderately slow.",
    difficulty: 'beginner',
  },
  {
    id: 26,
    question: "What does 'allegro' mean?",
    options: ["Very slow", "Moderate speed", "Fast and lively", "Very fast"],
    correctAnswer: 2,
    explanation: "Allegro means fast and lively.",
    difficulty: 'beginner',
  },
  {
    id: 27,
    question: "What does 'largo' mean?",
    options: ["Very slow and broad", "Fast", "Moderate", "Very fast"],
    correctAnswer: 0,
    explanation: "Largo means very slow and broad.",
    difficulty: 'beginner',
  },
  {
    id: 28,
    question: "What is a sharp?",
    options: ["Lowers a note by a half step", "Raises a note by a half step", "Raises a note by a whole step", "No change to the note"],
    correctAnswer: 1,
    explanation: "A sharp (♯) raises a note by a half step.",
    difficulty: 'beginner',
  },
  {
    id: 29,
    question: "What is a flat?",
    options: ["Lowers a note by a half step", "Raises a note by a half step", "Lowers a note by a whole step", "No change to the note"],
    correctAnswer: 0,
    explanation: "A flat (♭) lowers a note by a half step.",
    difficulty: 'beginner',
  },
  {
    id: 30,
    question: "What is a natural?",
    options: ["Cancels a sharp or flat", "Adds a sharp", "Adds a flat", "Raises by whole step"],
    correctAnswer: 0,
    explanation: "A natural (♮) cancels a sharp or flat, returning the note to its natural state.",
    difficulty: 'beginner',
  },
  {
    id: 31,
    question: "How many sharps are in the key of D major?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    explanation: "D major has 2 sharps: F# and C#.",
    difficulty: 'beginner',
  },
  {
    id: 32,
    question: "What is the relative minor of G major?",
    options: ["E minor", "F minor", "A minor", "B minor"],
    correctAnswer: 0,
    explanation: "E minor is the relative minor of G major, sharing the same key signature (1 sharp: F#).",
    difficulty: 'beginner',
  },
  {
    id: 33,
    question: "How many lines make up a treble clef staff?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 2,
    explanation: "A staff (both treble and bass) has 5 lines.",
    difficulty: 'beginner',
  },
  {
    id: 34,
    question: "What is the order of flats in key signatures?",
    options: ["B-E-A-D-G-C-F", "F-C-G-D-A-E-B", "C-F-Bb-Eb-Ab-Db-Gb", "A-D-G-C-F-Bb-Eb"],
    correctAnswer: 0,
    explanation: "The order of flats is B-E-A-D-G-C-F, which is the reverse of the order of sharps.",
    difficulty: 'beginner',
  },
  {
    id: 35,
    question: "What is a rest in music?",
    options: ["A pause or silence", "A type of note", "A dynamic marking", "A tempo marking"],
    correctAnswer: 0,
    explanation: "A rest indicates a pause or silence in music for a specific duration.",
    difficulty: 'beginner',
  },
  {
    id: 36,
    question: "How many beats does a whole rest receive in 4/4 time?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 3,
    explanation: "A whole rest receives 4 beats in 4/4 time, just like a whole note.",
    difficulty: 'beginner',
  },
  {
    id: 37,
    question: "What is an octave?",
    options: ["8 notes apart", "12 notes apart", "5 notes apart", "7 notes apart"],
    correctAnswer: 0,
    explanation: "An octave is the interval of 8 notes (12 half steps) where the higher note has double the frequency of the lower note.",
    difficulty: 'beginner',
  },
  {
    id: 38,
    question: "What are the names of the spaces in the treble clef?",
    options: ["A-C-E-G", "F-A-C-E", "E-G-B-D", "G-B-D-F"],
    correctAnswer: 1,
    explanation: "The spaces in the treble clef spell F-A-C-E (bottom to top).",
    difficulty: 'beginner',
  },
  {
    id: 39,
    question: "What are the names of the lines in the treble clef?",
    options: ["A-C-E-G-B", "F-A-C-E-G", "E-G-B-D-F", "G-B-D-F-A"],
    correctAnswer: 2,
    explanation: "The lines in the treble clef spell E-G-B-D-F (bottom to top), remembered as 'Every Good Boy Does Fine'.",
    difficulty: 'beginner',
  },
  {
    id: 40,
    question: "What are the names of the spaces in the bass clef?",
    options: ["A-C-E-G", "F-A-C-E", "E-G-B-D", "G-B-D-F"],
    correctAnswer: 0,
    explanation: "The spaces in the bass clef spell A-C-E-G (bottom to top), remembered as 'All Cows Eat Grass'.",
    difficulty: 'beginner',
  },
  {
    id: 41,
    question: "What are the names of the lines in the bass clef?",
    options: ["A-C-E-G-B", "F-A-C-E-G", "E-G-B-D-F", "G-B-D-F-A"],
    correctAnswer: 3,
    explanation: "The lines in the bass clef spell G-B-D-F-A (bottom to top), remembered as 'Good Boys Do Fine Always'.",
    difficulty: 'beginner',
  },
  {
    id: 42,
    question: "What is a chord?",
    options: ["A single note", "Three or more notes played together", "Two notes played together", "A rest"],
    correctAnswer: 1,
    explanation: "A chord is three or more notes played together simultaneously.",
    difficulty: 'beginner',
  },
  {
    id: 43,
    question: "What is a triad?",
    options: ["A chord with 2 notes", "A chord with 3 notes", "A chord with 4 notes", "A single note"],
    correctAnswer: 1,
    explanation: "A triad is a chord made up of three notes: root, third, and fifth.",
    difficulty: 'beginner',
  },
  {
    id: 44,
    question: "What are the three types of minor scales?",
    options: ["Natural, harmonic, melodic", "Major, minor, diminished", "Sharp, flat, natural", "Fast, slow, moderate"],
    correctAnswer: 0,
    explanation: "The three types of minor scales are natural, harmonic, and melodic minor.",
    difficulty: 'beginner',
  },
  {
    id: 45,
    question: "What is a scale?",
    options: ["A series of notes in ascending or descending order", "A single chord", "A rest", "A dynamic marking"],
    correctAnswer: 0,
    explanation: "A scale is a series of notes arranged in ascending or descending order, typically within an octave.",
    difficulty: 'beginner',
  },
  {
    id: 46,
    question: "How many notes are in a major scale?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 3,
    explanation: "A major scale has 8 notes (including the octave), following the pattern: whole-whole-half-whole-whole-whole-half steps.",
    difficulty: 'beginner',
  },
  {
    id: 47,
    question: "What is the pattern of intervals in a major scale?",
    options: ["W-W-H-W-W-W-H", "W-H-W-W-H-W-W", "H-W-W-H-W-W-W", "W-W-W-H-W-W-H"],
    correctAnswer: 0,
    explanation: "The pattern of intervals in a major scale is: Whole-Whole-Half-Whole-Whole-Whole-Half (W-W-H-W-W-W-H).",
    difficulty: 'beginner',
  },
  {
    id: 48,
    question: "What does 'ritardando' or 'ritard' mean?",
    options: ["Getting faster", "Getting slower", "Getting louder", "Getting softer"],
    correctAnswer: 1,
    explanation: "Ritardando (or ritard) means gradually getting slower.",
    difficulty: 'beginner',
  },
  {
    id: 49,
    question: "What does 'accelerando' mean?",
    options: ["Getting faster", "Getting slower", "Getting louder", "Getting softer"],
    correctAnswer: 0,
    explanation: "Accelerando means gradually getting faster.",
    difficulty: 'beginner',
  },
  {
    id: 50,
    question: "What is a fermata?",
    options: ["A sharp", "A hold or pause", "A tie", "A rest"],
    correctAnswer: 1,
    explanation: "A fermata (pause symbol) indicates to hold a note or rest longer than its written value.",
    difficulty: 'beginner',
  },
  // Add 150+ more beginner questions here...
  // For now, I'll add a note that more questions should be added
];

// INTERMEDIATE LEVEL QUESTIONS (200+ questions)
export const intermediateQuestions: QuizQuestion[] = [
  {
    id: 201,
    question: "How many half steps are in a perfect fifth?",
    options: ["5", "7", "9", "12"],
    correctAnswer: 1,
    explanation: "A perfect fifth contains 7 half steps (semitones).",
    difficulty: 'intermediate',
  },
  {
    id: 202,
    question: "Which interval is known as the 'devil's interval'?",
    options: ["Major 7th", "Diminished 5th", "Augmented 4th", "Both B and C"],
    correctAnswer: 3,
    explanation: "The tritone (diminished 5th/augmented 4th) was historically called the devil's interval because it's exactly half an octave.",
    difficulty: 'intermediate',
  },
  {
    id: 203,
    question: "How many sharps are in the key of E major?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 1,
    explanation: "E major has 4 sharps: F#, C#, G#, and D#.",
    difficulty: 'intermediate',
  },
  {
    id: 204,
    question: "What is a secondary dominant?",
    options: ["The V chord of a key", "The dominant chord of a non-tonic key area", "The I chord", "A diminished chord"],
    correctAnswer: 1,
    explanation: "A secondary dominant is the dominant (V) chord of a key other than the tonic, used to create temporary tonal centers.",
    difficulty: 'intermediate',
  },
  {
    id: 205,
    question: "What is a cadence?",
    options: ["A type of scale", "A chord progression that creates a sense of resolution", "A tempo marking", "A dynamic marking"],
    correctAnswer: 1,
    explanation: "A cadence is a chord progression that creates a sense of resolution or pause in music, often at the end of a phrase.",
    difficulty: 'intermediate',
  },
  {
    id: 206,
    question: "What is a perfect authentic cadence?",
    options: ["V-I with root position chords", "IV-I", "ii-V", "vi-V"],
    correctAnswer: 0,
    explanation: "A perfect authentic cadence is V-I (dominant to tonic) with both chords in root position and the tonic note in the highest voice.",
    difficulty: 'intermediate',
  },
  {
    id: 207,
    question: "What is the difference between a major and minor third?",
    options: ["1 half step", "2 half steps", "3 half steps", "4 half steps"],
    correctAnswer: 0,
    explanation: "A minor third has 3 half steps, while a major third has 4 half steps. The difference is 1 half step.",
    difficulty: 'intermediate',
  },
  {
    id: 208,
    question: "What is a diminished triad?",
    options: ["Minor third + minor third", "Minor third + major third", "Major third + minor third", "Major third + major third"],
    correctAnswer: 0,
    explanation: "A diminished triad consists of a minor third plus a minor third (e.g., C-Eb-Gb).",
    difficulty: 'intermediate',
  },
  {
    id: 209,
    question: "What is an augmented triad?",
    options: ["Minor third + minor third", "Minor third + major third", "Major third + minor third", "Major third + major third"],
    correctAnswer: 3,
    explanation: "An augmented triad consists of a major third plus a major third (e.g., C-E-G#).",
    difficulty: 'intermediate',
  },
  {
    id: 210,
    question: "How many sharps are in the key of B major?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 2,
    explanation: "B major has 5 sharps: F#, C#, G#, D#, and A#.",
    difficulty: 'intermediate',
  },
  {
    id: 211,
    question: "What is a modulation?",
    options: ["A dynamic change", "A tempo change", "A change of key", "A change of meter"],
    correctAnswer: 2,
    explanation: "A modulation is a change from one key to another within a piece of music.",
    difficulty: 'intermediate',
  },
  {
    id: 212,
    question: "What is a pivot chord?",
    options: ["A chord that belongs to both the old and new key", "The V chord", "The I chord", "A diminished chord"],
    correctAnswer: 0,
    explanation: "A pivot chord is a chord that functions in both the old key and the new key, facilitating a smooth modulation.",
    difficulty: 'intermediate',
  },
  {
    id: 213,
    question: "What is a seventh chord?",
    options: ["A chord with 6 notes", "A chord with 4 notes built in thirds", "A chord with 3 notes", "A single note"],
    correctAnswer: 1,
    explanation: "A seventh chord is a chord with 4 notes built in thirds: root, third, fifth, and seventh.",
    difficulty: 'intermediate',
  },
  {
    id: 214,
    question: "What is a dominant seventh chord?",
    options: ["I7", "V7", "IV7", "ii7"],
    correctAnswer: 1,
    explanation: "A dominant seventh chord is a major triad with a minor seventh added, typically built on the fifth degree (V7).",
    difficulty: 'intermediate',
  },
  {
    id: 215,
    question: "What is the harmonic minor scale?",
    options: ["Natural minor with raised 7th", "Natural minor with lowered 7th", "Major scale with lowered 3rd", "Natural minor unchanged"],
    correctAnswer: 0,
    explanation: "The harmonic minor scale raises the 7th degree of the natural minor scale by a half step.",
    difficulty: 'intermediate',
  },
  {
    id: 216,
    question: "What is the melodic minor scale?",
    options: ["Raises 6th and 7th ascending, natural minor descending", "Always raises 6th and 7th", "Lowers 6th and 7th", "Same as natural minor"],
    correctAnswer: 0,
    explanation: "The melodic minor scale raises the 6th and 7th degrees ascending, but uses the natural minor form descending.",
    difficulty: 'intermediate',
  },
  {
    id: 217,
    question: "What is a sequence?",
    options: ["A chord progression", "A melodic pattern repeated at different pitch levels", "A scale", "A cadence"],
    correctAnswer: 1,
    explanation: "A sequence is a melodic or harmonic pattern that is repeated at different pitch levels.",
    difficulty: 'intermediate',
  },
  {
    id: 218,
    question: "What is counterpoint?",
    options: ["A single melody line", "The combination of two or more independent melodic lines", "A chord", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "Counterpoint is the technique of combining two or more independent melodic lines that sound good together.",
    difficulty: 'intermediate',
  },
  {
    id: 219,
    question: "What is a suspension?",
    options: ["A chord change", "A non-chord tone that resolves down by step", "A tempo marking", "A key change"],
    correctAnswer: 1,
    explanation: "A suspension is a non-chord tone that is held over from a previous chord and resolves down by step.",
    difficulty: 'intermediate',
  },
  {
    id: 220,
    question: "What is a passing tone?",
    options: ["A chord tone", "A non-chord tone that connects two chord tones by step", "A rest", "A tie"],
    correctAnswer: 1,
    explanation: "A passing tone is a non-chord tone that connects two chord tones by stepwise motion.",
    difficulty: 'intermediate',
  },
  {
    id: 221,
    question: "What is an appoggiatura?",
    options: ["A non-chord tone approached by leap and resolved by step", "A passing tone", "A suspension", "A chord tone"],
    correctAnswer: 0,
    explanation: "An appoggiatura is a non-chord tone that is approached by leap and resolved by step in the opposite direction.",
    difficulty: 'intermediate',
  },
  {
    id: 222,
    question: "How many flats are in the key of Eb major?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 2,
    explanation: "Eb major has 3 flats: Bb, Eb, and Ab.",
    difficulty: 'intermediate',
  },
  {
    id: 223,
    question: "What is a circle of fifths?",
    options: ["A chord progression", "A visual representation of key relationships", "A scale", "A tempo marking"],
    correctAnswer: 1,
    explanation: "The circle of fifths is a visual representation showing the relationships between keys, arranged by ascending fifths.",
    difficulty: 'intermediate',
  },
  {
    id: 224,
    question: "What is a relative key relationship?",
    options: ["Keys with the same tonic", "Keys with the same key signature", "Keys a fifth apart", "Keys unrelated"],
    correctAnswer: 1,
    explanation: "Relative keys share the same key signature but have different tonics (e.g., C major and A minor).",
    difficulty: 'intermediate',
  },
  {
    id: 225,
    question: "What is a parallel key relationship?",
    options: ["Keys with the same tonic", "Keys with the same key signature", "Keys a fifth apart", "Keys unrelated"],
    correctAnswer: 0,
    explanation: "Parallel keys share the same tonic but have different key signatures (e.g., C major and C minor).",
    difficulty: 'intermediate',
  },
  {
    id: 226,
    question: "What is a Neapolitan chord?",
    options: ["A chord built on the raised second degree", "A major chord built on the lowered second degree", "The V chord", "The I chord"],
    correctAnswer: 1,
    explanation: "A Neapolitan chord is a major chord built on the lowered second degree (bII), typically in first inversion.",
    difficulty: 'intermediate',
  },
  {
    id: 227,
    question: "What is an augmented sixth chord?",
    options: ["A chord with an augmented sixth interval", "A diminished chord", "The V chord", "A seventh chord"],
    correctAnswer: 0,
    explanation: "An augmented sixth chord contains an augmented sixth interval and typically resolves to the dominant or tonic.",
    difficulty: 'intermediate',
  },
  {
    id: 228,
    question: "What is a pedal point?",
    options: ["A tempo marking", "A sustained or repeated note, usually in the bass", "A chord", "A melodic pattern"],
    correctAnswer: 1,
    explanation: "A pedal point (or pedal tone) is a sustained or repeated note, usually in the bass, while harmonies change above it.",
    difficulty: 'intermediate',
  },
  {
    id: 229,
    question: "What is a hemiola?",
    options: ["A chord progression", "A rhythmic device where 3 beats are felt as 2", "A scale", "A cadence"],
    correctAnswer: 1,
    explanation: "A hemiola is a rhythmic device where 3 beats of equal value are felt as 2 beats, or vice versa.",
    difficulty: 'intermediate',
  },
  {
    id: 230,
    question: "How many sharps are in the key of F# major?",
    options: ["4", "5", "6", "7"],
    correctAnswer: 2,
    explanation: "F# major has 6 sharps: F#, C#, G#, D#, A#, and E#.",
    difficulty: 'intermediate',
  },
  {
    id: 231,
    question: "What is a compound time signature?",
    options: ["Time signatures where the beat divides into 2", "Time signatures where the beat divides into 3", "4/4 time", "3/4 time"],
    correctAnswer: 1,
    explanation: "Compound time signatures (like 6/8, 9/8) have beats that divide into 3 equal parts.",
    difficulty: 'intermediate',
  },
  {
    id: 232,
    question: "What is a simple time signature?",
    options: ["Time signatures where the beat divides into 2", "Time signatures where the beat divides into 3", "6/8 time", "9/8 time"],
    correctAnswer: 0,
    explanation: "Simple time signatures (like 2/4, 3/4, 4/4) have beats that divide into 2 equal parts.",
    difficulty: 'intermediate',
  },
  {
    id: 233,
    question: "What is syncopation?",
    options: ["Regular rhythm", "Accenting weak beats or off-beats", "A tempo marking", "A dynamic marking"],
    correctAnswer: 1,
    explanation: "Syncopation is the accenting of weak beats or off-beats, creating unexpected rhythmic patterns.",
    difficulty: 'intermediate',
  },
  {
    id: 234,
    question: "What is a turn?",
    options: ["A chord", "An ornamental figure that turns around a note", "A rest", "A tie"],
    correctAnswer: 1,
    explanation: "A turn is an ornamental figure that turns around a principal note by playing the note above, the principal note, the note below, and the principal note again.",
    difficulty: 'intermediate',
  },
  {
    id: 235,
    question: "What is a trill?",
    options: ["A rapid alternation between two adjacent notes", "A chord", "A single note", "A rest"],
    correctAnswer: 0,
    explanation: "A trill is a rapid alternation between two adjacent notes, usually a semitone or tone apart.",
    difficulty: 'intermediate',
  },
  {
    id: 236,
    question: "What is a mordent?",
    options: ["A rapid alternation with an upper or lower neighbor note", "A chord", "A scale", "A cadence"],
    correctAnswer: 0,
    explanation: "A mordent is a rapid alternation between a note and an upper or lower neighbor note.",
    difficulty: 'intermediate',
  },
  {
    id: 237,
    question: "What is a grace note?",
    options: ["A chord tone", "A quick note that leads into a main note", "A rest", "A tie"],
    correctAnswer: 1,
    explanation: "A grace note is a quick ornamental note that leads into a main note, typically played very quickly.",
    difficulty: 'intermediate',
  },
  {
    id: 238,
    question: "What is a glissando?",
    options: ["A rapid slide between two notes", "A chord", "A single note", "A rest"],
    correctAnswer: 0,
    explanation: "A glissando is a rapid slide between two notes, playing all the intermediate pitches.",
    difficulty: 'intermediate',
  },
  {
    id: 239,
    question: "What is a portamento?",
    options: ["A smooth slide between notes", "A staccato note", "A chord", "A rest"],
    correctAnswer: 0,
    explanation: "A portamento is a smooth, continuous slide from one pitch to another, especially common in string and voice.",
    difficulty: 'intermediate',
  },
  {
    id: 240,
    question: "What is polyphony?",
    options: ["A single melody", "Music with multiple independent melodic lines", "A chord progression", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "Polyphony is musical texture with multiple independent melodic lines sounding simultaneously.",
    difficulty: 'intermediate',
  },
  {
    id: 241,
    question: "What is homophony?",
    options: ["Multiple independent melodies", "A single melody with chordal accompaniment", "A single melody only", "No melody"],
    correctAnswer: 1,
    explanation: "Homophony is musical texture with one main melody supported by chordal accompaniment.",
    difficulty: 'intermediate',
  },
  {
    id: 242,
    question: "What is monophony?",
    options: ["Multiple melodies", "A single melodic line without accompaniment", "Chordal texture", "Polyphonic texture"],
    correctAnswer: 1,
    explanation: "Monophony is musical texture with a single melodic line without accompaniment.",
    difficulty: 'intermediate',
  },
  {
    id: 243,
    question: "What is the mediant?",
    options: ["The 1st scale degree", "The 3rd scale degree", "The 5th scale degree", "The 7th scale degree"],
    correctAnswer: 1,
    explanation: "The mediant is the 3rd scale degree, located midway between the tonic and dominant.",
    difficulty: 'intermediate',
  },
  {
    id: 244,
    question: "What is the subdominant?",
    options: ["The 1st scale degree", "The 3rd scale degree", "The 4th scale degree", "The 5th scale degree"],
    correctAnswer: 2,
    explanation: "The subdominant is the 4th scale degree, located a fifth below the tonic.",
    difficulty: 'intermediate',
  },
  {
    id: 245,
    question: "What is the submediant?",
    options: ["The 3rd scale degree", "The 5th scale degree", "The 6th scale degree", "The 7th scale degree"],
    correctAnswer: 2,
    explanation: "The submediant is the 6th scale degree, located midway between the subdominant and tonic.",
    difficulty: 'intermediate',
  },
  {
    id: 246,
    question: "What is the leading tone?",
    options: ["The 1st scale degree", "The 5th scale degree", "The 6th scale degree", "The 7th scale degree"],
    correctAnswer: 3,
    explanation: "The leading tone is the 7th scale degree, which 'leads' strongly to the tonic.",
    difficulty: 'intermediate',
  },
  {
    id: 247,
    question: "What is an inverted cadence?",
    options: ["A cadence with inverted chords", "A deceptive cadence", "A plagal cadence", "A perfect cadence"],
    correctAnswer: 0,
    explanation: "An inverted cadence uses inverted chords (not in root position), such as V6-I.",
    difficulty: 'intermediate',
  },
  {
    id: 248,
    question: "What is a deceptive cadence?",
    options: ["V-I", "V-vi", "IV-I", "ii-V"],
    correctAnswer: 1,
    explanation: "A deceptive cadence is V-vi (or V-VI in minor), where the dominant resolves to a non-tonic chord, creating surprise.",
    difficulty: 'intermediate',
  },
  {
    id: 249,
    question: "What is a plagal cadence?",
    options: ["V-I", "IV-I", "ii-V", "vi-V"],
    correctAnswer: 1,
    explanation: "A plagal cadence is IV-I (subdominant to tonic), often called the 'Amen' cadence.",
    difficulty: 'intermediate',
  },
  {
    id: 250,
    question: "What is a half cadence?",
    options: ["A cadence ending on V", "A cadence ending on I", "IV-I", "V-vi"],
    correctAnswer: 0,
    explanation: "A half cadence (or imperfect cadence) ends on the dominant (V), creating a sense of incompleteness.",
    difficulty: 'intermediate',
  },
  // Add 150+ more intermediate questions here...
];

// ADVANCED LEVEL QUESTIONS (200+ questions)
export const advancedQuestions: QuizQuestion[] = [
  {
    id: 401,
    question: "What is a non-functional harmony?",
    options: ["Harmony that doesn't follow traditional voice leading", "V-I progressions", "Standard cadences", "Diatonic chords"],
    correctAnswer: 0,
    explanation: "Non-functional harmony doesn't follow traditional tonal voice leading and chord functions.",
    difficulty: 'advanced',
  },
  {
    id: 402,
    question: "What is a cluster chord?",
    options: ["A chord with notes close together", "A major triad", "A diminished chord", "A seventh chord"],
    correctAnswer: 0,
    explanation: "A cluster chord contains notes that are very close together (adjacent or nearly adjacent pitches), creating a dissonant sound.",
    difficulty: 'advanced',
  },
  {
    id: 403,
    question: "What is a polychord?",
    options: ["Two chords played simultaneously", "A single chord", "A chord progression", "A scale"],
    correctAnswer: 0,
    explanation: "A polychord is two different chords played at the same time, often notated as one chord over another.",
    difficulty: 'advanced',
  },
  {
    id: 404,
    question: "What is serialism?",
    options: ["A tonal technique", "A method of composition using a series of tones in a fixed order", "A chord progression", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "Serialism is a method of composition using a series of tones (or other musical elements) in a fixed order, such as the twelve-tone technique.",
    difficulty: 'advanced',
  },
  {
    id: 405,
    question: "What is the twelve-tone technique?",
    options: ["Using 12 different chords", "A method using all 12 chromatic pitches in a specific order", "A scale with 12 notes", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "The twelve-tone technique (or dodecaphony) uses all 12 chromatic pitches arranged in a specific order (tone row) that avoids tonal hierarchy.",
    difficulty: 'advanced',
  },
  {
    id: 406,
    question: "What is atonality?",
    options: ["Music without a tonal center", "Music in a major key", "Music in a minor key", "Music with simple harmony"],
    correctAnswer: 0,
    explanation: "Atonality is music that lacks a tonal center or key, avoiding traditional harmonic relationships.",
    difficulty: 'advanced',
  },
  {
    id: 407,
    question: "What is a tone row?",
    options: ["A chord", "An ordered series of the 12 chromatic pitches", "A scale", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "A tone row is an ordered series of the 12 chromatic pitches, used as the basis for twelve-tone composition.",
    difficulty: 'advanced',
  },
  {
    id: 408,
    question: "What is set theory in music?",
    options: ["A way to analyze chords using mathematical sets", "A chord progression", "A scale type", "A rhythm pattern"],
    correctAnswer: 0,
    explanation: "Set theory in music is a method of analyzing and categorizing pitch collections (chords, scales) using mathematical set theory.",
    difficulty: 'advanced',
  },
  {
    id: 409,
    question: "What is a pitch class set?",
    options: ["A collection of pitches without regard to octave", "A single chord", "A scale", "A rhythm pattern"],
    correctAnswer: 0,
    explanation: "A pitch class set is a collection of pitches without regard to octave, used in set theory analysis.",
    difficulty: 'advanced',
  },
  {
    id: 410,
    question: "What is quartal harmony?",
    options: ["Harmony based on fourths", "Harmony based on thirds", "Harmony based on fifths", "Harmony based on seconds"],
    correctAnswer: 0,
    explanation: "Quartal harmony is harmony built using intervals of fourths rather than the traditional thirds.",
    difficulty: 'advanced',
  },
  {
    id: 411,
    question: "What is quintal harmony?",
    options: ["Harmony based on fourths", "Harmony based on thirds", "Harmony based on fifths", "Harmony based on seconds"],
    correctAnswer: 2,
    explanation: "Quintal harmony is harmony built using intervals of fifths rather than the traditional thirds.",
    difficulty: 'advanced',
  },
  {
    id: 412,
    question: "What is bitonality?",
    options: ["One key", "Two different keys sounding simultaneously", "Three keys", "No key"],
    correctAnswer: 1,
    explanation: "Bitonality is the simultaneous use of two different keys in different parts of the music.",
    difficulty: 'advanced',
  },
  {
    id: 413,
    question: "What is polytonality?",
    options: ["One key", "Two keys", "Multiple keys sounding simultaneously", "No keys"],
    correctAnswer: 2,
    explanation: "Polytonality is the simultaneous use of multiple different keys in different parts of the music.",
    difficulty: 'advanced',
  },
  {
    id: 414,
    question: "What is a mode of limited transposition?",
    options: ["A scale that can only be transposed a few ways before repeating", "A major scale", "A minor scale", "Any scale"],
    correctAnswer: 0,
    explanation: "A mode of limited transposition is a scale that can only be transposed a limited number of ways before repeating itself (e.g., whole-tone scale, octatonic scale).",
    difficulty: 'advanced',
  },
  {
    id: 415,
    question: "What is the whole-tone scale?",
    options: ["A scale with all whole steps", "A major scale", "A minor scale", "A pentatonic scale"],
    correctAnswer: 0,
    explanation: "The whole-tone scale consists entirely of whole steps (major seconds), creating 6 notes before the octave.",
    difficulty: 'advanced',
  },
  {
    id: 416,
    question: "What is the octatonic scale?",
    options: ["An 8-note scale alternating whole and half steps", "A 7-note scale", "A 5-note scale", "A 12-note scale"],
    correctAnswer: 0,
    explanation: "The octatonic (or diminished) scale alternates whole and half steps, creating an 8-note scale.",
    difficulty: 'advanced',
  },
  {
    id: 417,
    question: "What is a tone cluster?",
    options: ["Notes spread far apart", "A group of adjacent notes played together", "A single note", "A chord in thirds"],
    correctAnswer: 1,
    explanation: "A tone cluster is a group of adjacent notes played together, creating a dense, dissonant sound.",
    difficulty: 'advanced',
  },
  {
    id: 418,
    question: "What is microtonality?",
    options: ["Using standard semitones", "Using intervals smaller than a semitone", "Using only whole tones", "Using only major thirds"],
    correctAnswer: 1,
    explanation: "Microtonality is the use of intervals smaller than a semitone (half step), such as quarter tones.",
    difficulty: 'advanced',
  },
  {
    id: 419,
    question: "What is just intonation?",
    options: ["Equal temperament", "A tuning system based on pure intervals", "A type of scale", "A chord type"],
    correctAnswer: 1,
    explanation: "Just intonation is a tuning system based on pure, mathematically simple intervals (ratios), rather than equal temperament.",
    difficulty: 'advanced',
  },
  {
    id: 420,
    question: "What is equal temperament?",
    options: ["A tuning system dividing the octave into 12 equal semitones", "Just intonation", "A chord type", "A scale type"],
    correctAnswer: 0,
    explanation: "Equal temperament divides the octave into 12 equal semitones, making all keys equally usable but slightly compromising pure intervals.",
    difficulty: 'advanced',
  },
  {
    id: 421,
    question: "What is a tone poem?",
    options: ["A chord progression", "A one-movement orchestral work that tells a story", "A scale", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "A tone poem (symphonic poem) is a one-movement orchestral work that tells a story or describes a scene.",
    difficulty: 'advanced',
  },
  {
    id: 422,
    question: "What is a leitmotif?",
    options: ["A chord", "A recurring musical theme associated with a character, idea, or emotion", "A scale", "A tempo marking"],
    correctAnswer: 1,
    explanation: "A leitmotif is a recurring musical theme associated with a specific character, idea, or emotion, famously used by Wagner.",
    difficulty: 'advanced',
  },
  {
    id: 423,
    question: "What is a passacaglia?",
    options: ["A chord progression", "A form based on a repeating bass line", "A scale", "A tempo marking"],
    correctAnswer: 1,
    explanation: "A passacaglia is a form based on a repeating bass line (ostinato) with variations above it.",
    difficulty: 'advanced',
  },
  {
    id: 424,
    question: "What is a chaconne?",
    options: ["A form with a repeating harmonic progression", "A single chord", "A scale", "A tempo marking"],
    correctAnswer: 0,
    explanation: "A chaconne is a form with a repeating harmonic progression over which variations are composed.",
    difficulty: 'advanced',
  },
  {
    id: 425,
    question: "What is a fugue?",
    options: ["A chord", "A contrapuntal form with a main subject and imitative entries", "A scale", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "A fugue is a contrapuntal form with a main subject (theme) that enters imitatively in different voices throughout the piece.",
    difficulty: 'advanced',
  },
  {
    id: 426,
    question: "What is a subject in a fugue?",
    options: ["A chord", "The main melodic theme of a fugue", "A scale", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "The subject is the main melodic theme of a fugue that appears in each voice.",
    difficulty: 'advanced',
  },
  {
    id: 427,
    question: "What is an answer in a fugue?",
    options: ["The subject transposed to the dominant", "A chord", "A scale", "A rhythm"],
    correctAnswer: 0,
    explanation: "The answer is the subject transposed to the dominant (usually), typically appearing in the second voice entry.",
    difficulty: 'advanced',
  },
  {
    id: 428,
    question: "What is a countersubject in a fugue?",
    options: ["A melodic line that accompanies the subject", "The subject itself", "A chord", "A scale"],
    correctAnswer: 0,
    explanation: "A countersubject is a melodic line that accompanies the subject (or answer) and may reappear throughout the fugue.",
    difficulty: 'advanced',
  },
  {
    id: 429,
    question: "What is a stretto?",
    options: ["Overlapping entries of the subject", "A chord", "A single note", "A rest"],
    correctAnswer: 0,
    explanation: "A stretto is a technique where subject entries overlap, creating increased intensity in a fugue.",
    difficulty: 'advanced',
  },
  {
    id: 430,
    question: "What is an episode in a fugue?",
    options: ["A section without the subject", "The subject entry", "A chord", "A scale"],
    correctAnswer: 0,
    explanation: "An episode is a transitional section in a fugue that doesn't contain the complete subject, often modulating to new keys.",
    difficulty: 'advanced',
  },
  {
    id: 431,
    question: "What is a sonata form?",
    options: ["A chord progression", "A three-part form: exposition, development, recapitulation", "A scale", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "Sonata form consists of three main sections: exposition (presenting themes), development (developing themes), and recapitulation (returning to the tonic).",
    difficulty: 'advanced',
  },
  {
    id: 432,
    question: "What is the exposition in sonata form?",
    options: ["The development section", "The section presenting main themes in different keys", "The recapitulation", "The coda"],
    correctAnswer: 1,
    explanation: "The exposition presents the main themes, typically with the first theme in the tonic and the second theme in the dominant (or relative major).",
    difficulty: 'advanced',
  },
  {
    id: 433,
    question: "What is the development section in sonata form?",
    options: ["The exposition", "The section that develops and transforms themes", "The recapitulation", "The coda"],
    correctAnswer: 1,
    explanation: "The development section takes themes from the exposition and develops, fragments, and transforms them, often modulating through various keys.",
    difficulty: 'advanced',
  },
  {
    id: 434,
    question: "What is the recapitulation in sonata form?",
    options: ["The exposition", "The development", "The return of themes in the tonic key", "The coda"],
    correctAnswer: 2,
    explanation: "The recapitulation returns the themes from the exposition, but now both themes are in the tonic key.",
    difficulty: 'advanced',
  },
  {
    id: 435,
    question: "What is a coda?",
    options: ["The beginning of a piece", "A concluding section after the main form", "The development", "The exposition"],
    correctAnswer: 1,
    explanation: "A coda is a concluding section that comes after the main form (like sonata form) to provide closure.",
    difficulty: 'advanced',
  },
  {
    id: 436,
    question: "What is a rondo form?",
    options: ["A-B-A form", "A form with a recurring main theme (A-B-A-C-A...)", "A single section", "A chord progression"],
    correctAnswer: 1,
    explanation: "Rondo form features a recurring main theme (A) alternating with contrasting sections (A-B-A-C-A...).",
    difficulty: 'advanced',
  },
  {
    id: 437,
    question: "What is a theme and variations?",
    options: ["A single theme", "A form with a theme followed by variations", "A chord progression", "A scale"],
    correctAnswer: 1,
    explanation: "Theme and variations is a form where a theme is presented and then followed by a series of variations that transform it.",
    difficulty: 'advanced',
  },
  {
    id: 438,
    question: "What is a scherzo?",
    options: ["A slow movement", "A fast, playful movement typically in 3/4 time", "A chord", "A scale"],
    correctAnswer: 1,
    explanation: "A scherzo is a fast, playful movement typically in 3/4 time, often replacing the minuet in later Classical and Romantic works.",
    difficulty: 'advanced',
  },
  {
    id: 439,
    question: "What is a double fugue?",
    options: ["A fugue with one subject", "A fugue with two subjects introduced simultaneously", "A simple fugue", "A chord progression"],
    correctAnswer: 1,
    explanation: "A double fugue is a fugue with two subjects that are introduced and developed simultaneously.",
    difficulty: 'advanced',
  },
  {
    id: 440,
    question: "What is a triple fugue?",
    options: ["A fugue with one subject", "A fugue with two subjects", "A fugue with three subjects", "A simple fugue"],
    correctAnswer: 2,
    explanation: "A triple fugue is a fugue with three subjects that are combined and developed together.",
    difficulty: 'advanced',
  },
  {
    id: 441,
    question: "What is a crab canon?",
    options: ["A chord", "A canon where one voice plays the melody forward and another plays it backward", "A scale", "A rhythm pattern"],
    correctAnswer: 1,
    explanation: "A crab canon (or retrograde canon) is a canon where one voice plays the melody forward and another plays it backward simultaneously.",
    difficulty: 'advanced',
  },
  {
    id: 442,
    question: "What is a mensuration canon?",
    options: ["A canon with the same tempo", "A canon with different time values (one voice faster or slower than another)", "A single melody", "A chord progression"],
    correctAnswer: 1,
    explanation: "A mensuration canon is a canon where voices have different time values, making one voice move faster or slower than another.",
    difficulty: 'advanced',
  },
  {
    id: 443,
    question: "What is a palindrome in music?",
    options: ["Music that sounds the same forward and backward", "A chord", "A scale", "A rhythm pattern"],
    correctAnswer: 0,
    explanation: "A palindrome is music that sounds the same when played forward and backward (melodically or structurally).",
    difficulty: 'advanced',
  },
  {
    id: 444,
    question: "What is isorhythm?",
    options: ["A chord type", "A Medieval technique using a repeating rhythmic pattern with different pitches", "A scale", "A tempo marking"],
    correctAnswer: 1,
    explanation: "Isorhythm is a Medieval technique where a repeating rhythmic pattern (talea) is combined with a repeating pitch pattern (color), often with different lengths creating complex relationships.",
    difficulty: 'advanced',
  },
  {
    id: 445,
    question: "What is a hocket?",
    options: ["A single continuous line", "A technique where notes alternate rapidly between voices", "A chord", "A scale"],
    correctAnswer: 1,
    explanation: "A hocket is a Medieval technique where a single melodic line is split between voices, with notes alternating rapidly.",
    difficulty: 'advanced',
  },
  {
    id: 446,
    question: "What is a tone row transformation (retrograde)?",
    options: ["Playing the row forward", "Playing the row backward", "Inverting the row", "Transposing the row"],
    correctAnswer: 1,
    explanation: "Retrograde is playing the tone row backward, from last note to first.",
    difficulty: 'advanced',
  },
  {
    id: 447,
    question: "What is a tone row transformation (inversion)?",
    options: ["Playing backward", "Mirroring the intervals (up becomes down, down becomes up)", "Transposing", "Repeating"],
    correctAnswer: 1,
    explanation: "Inversion mirrors the intervals of the tone row - what goes up now goes down by the same interval, and vice versa.",
    difficulty: 'advanced',
  },
  {
    id: 448,
    question: "What is a tone row transformation (retrograde inversion)?",
    options: ["Just retrograde", "Just inversion", "Inversion played backward", "Original row"],
    correctAnswer: 2,
    explanation: "Retrograde inversion combines both transformations - the inverted row is played backward.",
    difficulty: 'advanced',
  },
  {
    id: 449,
    question: "What is total serialism?",
    options: ["Serializing only pitch", "Applying serial principles to all musical elements (pitch, rhythm, dynamics, etc.)", "A tonal technique", "A chord progression"],
    correctAnswer: 1,
    explanation: "Total serialism applies serial principles to all musical elements, not just pitch - including rhythm, dynamics, timbre, etc.",
    difficulty: 'advanced',
  },
  {
    id: 450,
    question: "What is indeterminacy in music?",
    options: ["Fully notated music", "Music with elements left to chance or performer choice", "A chord progression", "A scale"],
    correctAnswer: 1,
    explanation: "Indeterminacy (or aleatoric music) includes elements left to chance, performer choice, or other non-deterministic factors.",
    difficulty: 'advanced',
  },
  // Add 150+ more advanced questions here...
];

// Combine all questions
export const allQuestions: QuizQuestion[] = [
  ...beginnerQuestions,
  ...intermediateQuestions,
  ...advancedQuestions,
];

// Get questions by difficulty
export function getQuestionsByDifficulty(difficulty: Difficulty): QuizQuestion[] {
  switch (difficulty) {
    case 'beginner':
      return beginnerQuestions;
    case 'intermediate':
      return intermediateQuestions;
    case 'advanced':
      return advancedQuestions;
    default:
      return beginnerQuestions;
  }
}
